#!/usr/bin/env sh

set -e

ROOT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
COMMAND="$ROOT_DIR/commands/$1.sh"
SETUP_MODE="default"

# load .env file if it exists
if [ -f "$ROOT_DIR/.env" ]
then
  export $(cat .env | xargs)
fi

if [ -e "$COMMAND" ]; then
  bash "$COMMAND" "$ROOT_DIR" "$SETUP_MODE"
else
  echo "$1 is no defined command"
fi