font_family Fira Code Medium
font_size 13.0
adjust_line_height 120%
include kanagawa-theme.conf
enable_audio_bell no

map cmd+c copy_to_clipboard
map cmd+p paste_from_clipboard

allow_remote_control yes

macos_show_window_title_in none
masos_titlebar_color background

tab_title_template "{index}: {title}"
window_margin_width 15
